export const NestInvitesErrorCodes = {
  ALREADY_INVITED: 'ALREADY_INVITED',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_NOT_PENDING: 'INVITE_NOT_PENDING',
  INVITES_NOT_ALLOWED: 'INVITES_NOT_ALLOWED',
} as const
