export const NestBansErrorCodes = {
  BAN_NOT_FOUND: 'BAN_NOT_FOUND',
  ALREADY_BANNED: 'ALREADY_BANNED',
  USER_BANNED: 'USER_BANNED',
  CANNOT_BAN_YOURSELF: 'CANNOT_BAN_YOURSELF',
  CANNOT_UNBAN_YOURSELF: 'CANNOT_UNBAN_YOURSELF',
} as const
