export const CommonErrorCodes = {
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVALID_CURSOR: 'INVALID_CURSOR',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
} as const
