export const NestPayoutErrorCodes = {
  PAYOUT_ACCOUNT_NOT_CONNECTED: 'PAYOUT_ACCOUNT_NOT_CONNECTED',
  PAYOUTS_NOT_ENABLED: 'PAYOUTS_NOT_ENABLED',
  NOTHING_TO_WITHDRAW: 'NOTHING_TO_WITHDRAW',
} as const
