export const AuthErrorCodes = {
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_SUPERSEDED: 'TOKEN_SUPERSEDED',
  TOKEN_ALREADY_REDEEMED: 'TOKEN_ALREADY_REDEEMED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SAME_PASSWORD: 'SAME_PASSWORD',
} as const
