export const NestMembersErrorCodes = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  ALREADY_A_MEMBER: 'ALREADY_A_MEMBER',
  CANNOT_REMOVE_YOURSELF: 'CANNOT_REMOVE_YOURSELF',
  CANNOT_LEAVE_AS_OWNER: 'CANNOT_LEAVE_AS_OWNER',
  CANNOT_CHANGE_YOUR_OWN_ROLE: 'CANNOT_CHANGE_YOUR_OWN_ROLE',
  MEMBER_ROLE_UNCHANGED: 'MEMBER_ROLE_UNCHANGED',
  CANNOT_MANAGE_HIGHER_ROLE_MEMBER: 'CANNOT_MANAGE_HIGHER_ROLE_MEMBER',
  CANNOT_ASSIGN_HIGHER_OR_EQUAL_ROLE: 'CANNOT_ASSIGN_HIGHER_OR_EQUAL_ROLE',
} as const
