export const NestJoinRequestsErrorCodes = {
  JOIN_REQUESTS_NOT_ACCEPTED: 'JOIN_REQUESTS_NOT_ACCEPTED',
  ALREADY_HAS_PENDING_JOIN_REQUEST: 'ALREADY_HAS_PENDING_JOIN_REQUEST',
  JOIN_REQUEST_NOT_PENDING: 'JOIN_REQUEST_NOT_PENDING',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
} as const
