export const PlatformReportErrorCodes = {
  PLATFORM_REPORT_NOT_FOUND: 'PLATFORM_REPORT_NOT_FOUND',
  PLATFORM_REPORT_ALREADY_RESOLVED: 'PLATFORM_REPORT_ALREADY_RESOLVED',
  PLATFORM_REPORT_TARGET_NOT_FOUND: 'PLATFORM_REPORT_TARGET_NOT_FOUND',
  ALREADY_REPORTED_TO_PLATFORM: 'ALREADY_REPORTED_TO_PLATFORM',
} as const
