export const NestsErrorCodes = {
  NEST_NOT_FOUND: 'NEST_NOT_FOUND',
  NEST_SLUG_TAKEN: 'NEST_SLUG_TAKEN',
  NEST_SLUG_RESERVED: 'NEST_SLUG_RESERVED',
  NEST_LIMIT_REACHED: 'NEST_LIMIT_REACHED',
  CANNOT_TRANSFER_OWNERSHIP_TO_SELF: 'CANNOT_TRANSFER_OWNERSHIP_TO_SELF',
  TARGET_USER_NOT_MEMBER: 'TARGET_USER_NOT_MEMBER',
} as const
