export const ChatErrorCodes = {
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  CANNOT_CHAT_WITH_YOURSELF: 'CANNOT_CHAT_WITH_YOURSELF',
  CANNOT_MESSAGE_BLOCKED_USER: 'CANNOT_MESSAGE_BLOCKED_USER',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  REPLY_TARGET_NOT_IN_CHAT: 'REPLY_TARGET_NOT_IN_CHAT',
} as const
